### ISSUE TITLE
Sticky slider control

### ISSUE THREAD

**Issue by meganmckissack** [hackoregon/component-library#67]
Slider controller to change year, stay's sticky to follow the user as they scroll down to other sections.

Can likely use slider already in the component library

need to clarify what the "play over time" button does

![sticky-slider-budget](https://cloud.githubusercontent.com/assets/2355543/24981538/083344d6-1f92-11e7-8157-c7cb84110055.png)

**Comment by palmerev** [comment]
@meganmckissack I've addressed this for the budget team project specifically, using the `rc-slider` and `react-sticky` packages. I couldn't use the Slider from the component library, because it's set up for a continuous range rather than independent values (e.g. years), and has an integrated tooltip that I didn't need. Honestly, I think the Slider itself should be removed from the component library, because the `rc-slider` is useful on it's own, and we don't get much out of baking in the tooltip and configuration ourselves. However, it might be useful to have some generic slider tooltips that could take custom styles. Not critical for the budget team, though.

**Comment by drabelpdx** [comment]
I'll set my version aside. Where is your's Evan, I'd like to see the code and compare approach.
Thanks  -David
